package org.zhxf.sale.domain;
// Generated 2019-6-14 11:15:34 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StoreItemsaleId generated by hbm2java
 */
@Embeddable
public class StoreItemsaleId implements java.io.Serializable {

	private String storeNo;
	private String itemNo;

	public StoreItemsaleId() {
	}

	public StoreItemsaleId(String storeNo, String itemNo) {
		this.storeNo = storeNo;
		this.itemNo = itemNo;
	}

	@Column(name = "Store_no", nullable = false, length = 13)
	public String getStoreNo() {
		return this.storeNo;
	}

	public void setStoreNo(String storeNo) {
		this.storeNo = storeNo;
	}

	@Column(name = "Item_no", nullable = false, length = 13)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StoreItemsaleId))
			return false;
		StoreItemsaleId castOther = (StoreItemsaleId) other;

		return ((this.getStoreNo() == castOther.getStoreNo()) || (this.getStoreNo() != null
				&& castOther.getStoreNo() != null && this.getStoreNo().equals(castOther.getStoreNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this.getItemNo() != null
						&& castOther.getItemNo() != null && this.getItemNo().equals(castOther.getItemNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStoreNo() == null ? 0 : this.getStoreNo().hashCode());
		result = 37 * result + (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		return result;
	}

}
